package.json
packages/stencil/package.json
packages/stencil/src/builders/utils/stencil-runtime.ts
packages/stencil/src/schematics/add-outputtarget/add-outputtarget.schema.json
packages/stencil/src/schematics/add-outputtarget/add-outputtarget.ts
packages/stencil/src/utils/versions.ts
yarn.lock

Add vue outputtarget using @nx-plus/vue
fix #47

feat(stencil): add vue outputtarget

---

e2e/svelte-e2e/tests/svelte.test.ts
package.json
packages/svelte/package.json
packages/svelte/src/builders/utils/normalize.ts
packages/svelte/src/builders/utils/rollup.ts
packages/svelte/src/schematics/application/application.ts
packages/svelte/src/schematics/application/lib/add-cypress.ts
tools/scripts/create-playground.ts
yarn.lock

fix(svelte): with directories the cypress config not created properly

---

e2e/stencil-e2e/tests/stencil.test.ts
packages/stencil/src/schematics/library/lib/update-tsconfig.ts
packages/stencil/src/schematics/library/schema.d.ts
packages/stencil/src/schematics/library/schema.json
packages/stencil/src/schematics/library/schematic.spec.ts
packages/stencil/src/schematics/library/schematic.ts
packages/stencil/src/schematics/make-lib-buildable/files/lib/package.json.template
packages/stencil/src/schematics/make-lib-buildable/make-lib-buildable.spec.ts
packages/stencil/src/schematics/make-lib-buildable/make-lib-buildable.ts
packages/stencil/src/schematics/make-lib-buildable/schema.d.ts
packages/stencil/src/schematics/make-lib-buildable/schema.json

feat(stencil): add publishable to libraries

---

e2e/stencil-e2e/tests/stencil.test.ts
packages/docs-docusaurus/docs/svelte/builder/build.md
packages/svelte/src/executors/build/builder.spec.ts
packages/svelte/src/executors/build/schema.d.ts
packages/svelte/src/executors/build/schema.json
packages/svelte/src/executors/utils/normalize.ts
packages/svelte/src/executors/utils/rollup-options.ts
packages/svelte/src/executors/utils/run-rollup-watch.ts
packages/tailwind/package.json
packages/tailwind/src/schematics/stencil/schematic.ts

feat(svelte): add devserver header options

---

packages/svelte/package.json
packages/svelte/src/executors/utils/run-rollup-watch.ts
packages/svelte/src/executors/utils/run-rollup.ts
packages/svelte/src/generators/component/lib/create-component-in-project.ts

refactor(svelte): remove angular devkit references

---

packages/stencil/src/executors/stencil-runtime/stencil-config.ts
packages/stencil/src/executors/stencil-runtime/stencil-runtime.ts

fix(stencil): fix windows paths to prevent broken builds

---

e2e/sveltekit-e2e/tests/sveltekit.spec.ts
packages/sveltekit/generators.json
packages/sveltekit/package.json

Hello 👋.
I fixed the component generator for sveltekit. 
I need to add more e2e tests before merging. And also figure out why Windows build does not pass

fix(sveltekit): repair component generator

---

packages/stencil/package.json
packages/stencil/src/generators/make-lib-buildable/files/lib/src/index.html.template
packages/stencil/src/generators/make-lib-buildable/make-lib-buildable.spec.ts
packages/stencil/src/generators/make-lib-buildable/make-lib-buildable.ts

Add www outputTarget and index.html file
ISSUES CLOSED: #256

feat(stencil): make buildable lib servable

---

packages/svelte/src/generators/component/component.spec.ts
packages/svelte/src/generators/component/lib/add-exports-to-barrel.ts

fix(svelte): fix svelte library barrel export

---

packages/stencil/src/generators/add-outputtarget/add-angular/generator.ts
packages/stencil/src/generators/add-outputtarget/add-outputtarget.spec.ts
packages/stencil/src/generators/add-outputtarget/add-react/generator.ts
packages/stencil/src/generators/add-outputtarget/add-vue/generator.ts
packages/stencil/src/generators/add-outputtarget/schema.d.ts
packages/stencil/src/generators/add-outputtarget/schema.json

fix(stencil): add importPath for outputtargets

---

packages/vite/migrations.json
packages/vite/package.json
packages/vite/project.json
packages/vite/src/executors/dev/executor.ts
packages/vite/src/migrations/vite-explict-config-file/vite-explict-config-file.ts

fix: repair current dev vite excutor

feat: add migration for explicit declare vite.config.js

---

packages/svelte/src/generators/application/files/index.html.template

fix(svelte): remove useless /public/ in static assets path

---

docs/docs/solid/overview.md

docs(solid): fixed link to official SolidJS page

docs(solid): fixed link to official SolidJS page

---

packages/angular/src/generators/application/application.ts
packages/angular/src/generators/application/files/index.html__tmpl__

Signed-off-by: Jordan Hall <Jordan@libertyware.co.uk>

fix: index.html should have prefix as root

---

package.json
packages/svelte/package.json
packages/vite/package.json
yarn.lock

fix(svelte): fix peerdependency of rxjs-for-await

---

packages/vite/README.md

Fix readme bug

---

docs/docs/sveltekit/overview.md

Switch from vitest to sveltekit in description.

Update overview.md for SvelteKit

---

packages/sveltekit/README.md
packages/sveltekit/src/generators/application/lib/install-dependencies.ts
packages/sveltekit/src/generators/utils/versions.ts

Resolves #580 and adds some documentation for Sveltekit package.

Add missing dependency for SvelteKit (@angular-devkit/schematics), update docs

---

packages/ts.ed/package.json

Generators should work properly after update

Update dev dependencies

---

docs/docs/vite/executors.md
packages/vite/src/executors/build/executor.ts
packages/vite/src/executors/build/schema.d.ts
packages/vite/src/executors/build/schema.json
packages/vite/src/executors/dev/executor.ts
packages/vite/src/executors/dev/schema.d.ts
packages/vite/src/executors/dev/schema.json
packages/vite/src/executors/package/package.impl.ts
packages/vite/src/generators/application/application.ts
packages/vite/src/generators/application/lib/add-project.ts
packages/vite/src/generators/application/lib/create-application-files.ts
packages/vite/src/generators/application/lib/normalize-options.ts
packages/vite/src/generators/application/schema.d.ts

fix(vite): read outputPath parameter

---

packages/react/src/generators/application/files/src/app/__fileName__.tsx__tmpl__

The `NxWelcome` component required a property called `title`, we need to create a component called App and provide the props to fix typing error and unit test

React: update template to fix typing error and unit test

---

packages/solid/package.json

Updated solid workspace to reference [latest solid-js version](https://www.npmjs.com/package/solid-js) 1.4.1. 
Ran unit and e2e tests successfully.

update solid to 1.4.1

---

packages/stencil/src/generators/application/lib/add-cypress.ts

fix(stencil): fix cypress is not found

---

packages/sveltekit/src/generators/application/files/src/app.html__template__

also %svelte.body% to %sveltekit.body%

Change %svelte.head% to %sveltekit.head%

---

packages/react/package.json
packages/vite/package.json

Signed-off-by: Jordan Hall <jordan@libertyware.co.uk>

fix: minor update released beta by mistake

---

docs/docs/ionic-angular/generators.md
e2e/ionic-angular-e2e/project.json
e2e/ionic-angular-e2e/tests/ionic-angular.spec.ts
packages/ionic-angular/src/generators/application/schema.json

Signed-off-by: Jordan Hall <Jordan@lts.sh>

testing(ionic): enable angular e2e

---

.husky/pre-push
CONTRIBUTING.md
README.md
packages/ionic-angular/README.md

Partial fix for https://github.com/nxext/nx-extensions/issues/869
Fix https://github.com/nxext/nx-extensions/issues/872

Update Ionic Angular docs

---

packages/capacitor/src/executors/cap/executor.ts

fix(capacitor): use installed cli to execute commands

---

packages/capacitor/src/executors/cap/executor.ts

Fix for https://github.com/nxext/nx-extensions/issues/962

fix: Invert the preserveNodeModules option

---

e2e/svelte-e2e/tests/application.test.ts
e2e/svelte-e2e/tests/library.test.ts
packages/svelte/generators.json
packages/svelte/package.json
packages/svelte/src/generators/init/init.ts
packages/svelte/src/generators/utils/add-plugin-to-nx-json.ts
packages/svelte/src/graph/TypeScriptSvelteImportLocator.ts
packages/svelte/src/graph/processProjectGraph.ts
packages/svelte/src/index.ts
packages/vue/src/generators/component/component.ts
packages/vue/src/generators/library/library.ts
packages/vue/src/generators/storybook-configuration/configuration.ts

feat(svelte): add project graph support

---

packages/preact/package.json
packages/preact/src/generators/component/component.spec.ts
packages/preact/src/generators/component/lib/add-exports-to-barrel.ts
packages/preact/src/generators/library/lib/add-project.ts
packages/preact/src/generators/utils/testing.ts
packages/sveltekit/package.json
packages/sveltekit/src/generators/application/generator.ts
packages/sveltekit/src/generators/component/lib/add-exports-to-barrel.ts

remove unnecessary nx/workspace reference

---

packages/stencil/package.json
packages/stencil/src/generators/add-outputtarget/add-angular/generator.ts
packages/stencil/src/generators/add-outputtarget/add-react/generator.ts
packages/stencil/src/generators/add-outputtarget/add-svelte/generator.ts
packages/stencil/src/utils/utillities.ts

fix(stencil): remove gitignore addage

---

packages/capacitor/src/generators/configuration/generator.spec.ts
packages/capacitor/src/generators/configuration/lib/add-dependencies.ts
packages/capacitor/src/generators/configuration/lib/update-project-package-json.ts
packages/ionic-angular/package.json
packages/ionic-angular/src/generators/configuration/generator.spec.ts
packages/ionic-angular/src/generators/configuration/lib/add-dependencies.ts
packages/ionic-angular/src/generators/configuration/lib/normalize-options.ts
packages/ionic-angular/src/utils/versions.ts
tools/scripts/create-playground.ts
tools/scripts/update-playground.ts
tools/scripts/utils.ts

Various fixes for Ionic and Capacitor plugins

---

packages/preact/src/generators/application/application.ts
packages/preact/src/generators/component/component.ts
packages/preact/src/generators/init/init.ts
packages/preact/src/generators/library/library.ts
packages/solid/src/generators/application/application.ts
packages/solid/src/generators/component/component.ts
packages/solid/src/generators/init/init.ts
packages/solid/src/generators/library/library.ts
packages/stencil/src/generators/add-outputtarget/add-angular/generator.ts
packages/stencil/src/generators/add-outputtarget/add-outputtarget.ts
packages/stencil/src/generators/add-outputtarget/add-react/generator.ts
packages/stencil/src/generators/application/generator.ts
packages/stencil/src/generators/component/component.ts
packages/stencil/src/generators/init/init.ts
packages/stencil/src/generators/library/generator.ts
packages/stencil/src/generators/make-lib-buildable/make-lib-buildable.ts
packages/stencil/src/generators/storybook-configuration/generator.ts
packages/svelte/src/generators/application/application.ts
packages/svelte/src/generators/component/component.ts
packages/svelte/src/generators/init/init.ts
packages/svelte/src/generators/library/library.ts
packages/svelte/src/generators/storybook-configuration/configuration.ts
packages/sveltekit/src/generators/application/generator.ts
packages/sveltekit/src/generators/component/component.ts
packages/sveltekit/src/generators/library/library.ts
packages/sveltekit/src/generators/route/route.ts

Bugs: implementation is not a function - add default export for all the generators

---

packages/capacitor/package.json
packages/capacitor/src/generators/configuration/generator.ts
packages/ionic-angular/package.json
packages/ionic-angular/src/generators/configuration/generator.ts
packages/ionic-react/package.json
packages/ionic-react/src/generators/configuration/generator.ts
packages/preact/src/generators/application/application.ts
packages/preact/src/generators/component/component.ts
packages/preact/src/generators/init/init.ts
packages/preact/src/generators/library/library.ts
packages/solid/src/generators/application/application.ts
packages/solid/src/generators/component/component.ts
packages/solid/src/generators/init/init.ts
packages/solid/src/generators/library/library.ts
packages/stencil/src/generators/add-outputtarget/add-outputtarget.ts
packages/stencil/src/generators/application/generator.ts
packages/stencil/src/generators/component/component.ts
packages/stencil/src/generators/init/init.ts
packages/stencil/src/generators/library/generator.ts
packages/stencil/src/generators/make-lib-buildable/make-lib-buildable.ts
packages/stencil/src/generators/storybook-configuration/generator.ts
packages/svelte/src/generators/application/application.ts
packages/svelte/src/generators/component/component.ts
packages/svelte/src/generators/init/init.ts
packages/svelte/src/generators/library/library.ts
packages/svelte/src/generators/storybook-configuration/configuration.ts
packages/sveltekit/src/generators/application/generator.ts
packages/sveltekit/src/generators/component/component.ts
packages/sveltekit/src/generators/library/library.ts
packages/sveltekit/src/generators/route/route.ts

I straight up forgot about the assertion  against `--preset=ts` 😢

Chore: add assert-not-using-ts-solution-setup to the generators

---

packages/stencil/src/generators/library/generator.ts

fix(stencil): init js libs when creating stencil lib

---

packages/capacitor/src/generators/configuration/generator.spec.ts
packages/capacitor/src/generators/configuration/lib/normalize-options.ts

fix(capacitor): align default web-dir for esbuild executor

---

packages/ionic-react/package.json

Sorry for the 3 PRs, I was sure the 3 commits would be into one PR :-\

fix(url): update docs url
