nxext/nx-extensions

libs/stencil/src/schematics/storybook/init/files/lib/.storybook/config.ts.template, libs/stencil/src/schematics/storybook/init/init.ts
Fixes storybook config.ts template referring to a hard-coded library name "library" instead of the provided project name.
=> fix(Storybook): replace hard-coded library name in storybook config

libs/stencil/src/schematics/library/files/lib/stencil.config.ts.template
Modify stencil.config to explicitly use the outer dist folder. This consolidates all build artifacts
=> fix(stencil.config): set explicit directory for library build

packages/stencil/src/schematics/component/files/src/__componentFileName__.spec.tsx.template
First of all, thank you very much for this awesome project :fire::pray:
There is a unnecessary < in the spec template for generating components thats generate following error.
=> delete unnecessary < in spec template

packages/stencil/src/schematics/component/files/src/__componentFileName__.spec.tsx.template
This PR adds a previously missing `<` in the html in the first test of the spec file template.
=> Add required < in spec file html

packages/stencil/src/builders/utils/stencil-runtime.ts
fix #54
Replacing `projectRoot` in the normalized `values.config.devServer.root` does not work, if `projectRoot` is not normalized as well. The replacement value will be normalized by the surrounding `normalize` call.
This issue can be reproduced on windows machines where `values.projectRoot` is a Windows-formatted path whereas `normalize(values.config.devServer.root)` returns a Unix-formatted path.
=> fix(dev-server): normalize project root before replacement

packages/svelte/src/builders/utils/rollup.ts
Add terser to production builds for Svelte (rollup).
BREAKING CHANGE: this may have the potential to break some builds as the output (hash)
will be different. It will also remove any comments in the output bundles.
=> feat(svelte): add terser for production builds

packages/stencil/src/builders/build/builder.ts, packages/stencil/src/builders/e2e/builder.ts, packages/stencil/src/builders/stencil-runtime/stencil-process.ts, packages/stencil/src/builders/test/builder.ts
This PR enables some minimal error logging when the Stencil builder fails.
Kind of short on time right this second, but this could probably be enhanced by adding a stack trace if the `--debug` flag is enabled.
=> Enable error reporting

.github/workflows/ci-checks-ubuntu.yml, .github/workflows/ci-checks-windows.yml, e2e/stencil-e2e/tests/stencil.test.ts, e2e/svelte-e2e/tests/svelte.test.ts, e2e/svelte-e2e/tsconfig.json, e2e/sveltekit-e2e/tests/sveltekit.spec.ts, e2e/sveltekit-e2e/tsconfig.json, nx.json, package.json, packages/stencil/src/executors/stencil-runtime/stencil-runtime.ts, packages/stencil/src/generators/make-lib-buildable/make-lib-buildable.spec.ts, packages/svelte/src/generators/application/files/vite.config.js.template, tsconfig.base.json, workspace.json, yarn.lock
Hey!
Thanks for your great work. We use this plugin for a while already - recently we have the need to set a custom `types` entrypoint. While this works nicely in plain stencil repos, we noticed that it doesn't work within a NX monorepo. The reason is, that it will be overridden by the default config of this plugin.
To fix this, we propose to keep the existing `package.json` entrypoints and to only use the default values if the properties are not set.
While preparing this fix I noticed that the husky pre-commit hook is not working correctly - let me know if I should move the husky fix to a separate PR.
Happy to get your feedback!
=> fix(stencil): keep existing entrypoint config

packages/sveltekit/package.json
Hello there 👋 
I was trying to install and use it (and might contribute later).
And it seems there is a missing dep to initiate a project 
The actual is behavior is when you run this command
```
nx g @nxext/sveltekit:app blog
```
it throws `"@angular-devkit/schematics` is missing.
Adding this dep in the package.json solve my issue ^^"
=> fix(sveltekit): add missing dep

packages/docs-docusaurus/docs/vite/executors/serve.md, packages/docs-docusaurus/docs/vite/overview.md, packages/vite/src/executors/dev/executor.ts, packages/vite/src/executors/dev/schema.d.ts, packages/vite/src/executors/dev/schema.json
This starts to address the issue with #305.
How to use:
Add proxy.conf.json into your project root
Example proxy.conf.json:
```
{
"/foo": "http://localhost:4567",
"/api": {
"target": "http://jsonplaceholder.typicode.com",
"changeOrigin": true,
}
}
```
Things to do after PR:
Migration script for svelte from rollbar over to vite.
=> feat: add proxy support for dev build

packages/sveltekit/src/generators/component/schema.json
It no longer supports 'id' so instead '$id'.
=> Updating schema.json on generators/components.

packages/sveltekit/package.json
To allow using patch-package with your package, your version should be comparable with semver
=> Fix version to pass semver check

packages/sveltekit/src/generators/application/files/src/app.html__template__
This fixes minor issues in the HTML template where the preprocessor wants %sveltekit.body% instead of %svelte.body%
e2e failed before, but passes with this change.
=> minor fixes svelte -> sveltekit

docs/docs/nxext/community.md
as per @Jordan-Hall's message here: https://github.com/nxext/nx-extensions/discussions/453#discussioncomment-2121765, I've just joined the server successfully with this link.
=> fix: set correct Discord server invitation link

docs/docs/ionic-angular/capacitor.md, docs/docs/ionic-react/capacitor.md, packages/capacitor/src/executors/cap/executor.ts
As stated in following [nxtend issue](https://github.com/nxtend-team/nxtend/issues/643), applicable also to nxext for nx 14+, the capacitor plugin can try to use wrong `cap` executable since it cannot know which package this executable is referenced to. It happened in our project and tied to run `cap` package (capturing socket packages) which is the wrong executable.
So the solution is simply to add the `--package` option with `@capacitor/cli` package to ensure NPX will use the executable from proper package, as stated as per NPX docs.
=> fix(capacitor): ensure npx uses @capacitor/cli executable

packages/capacitor/src/executors/cap/executor.ts, packages/stencil/src/generators/storybook-configuration/generator.ts, packages/svelte/src/generators/utils/targets.ts, packages/sveltekit/src/executors/add/executor.ts, packages/sveltekit/src/executors/sveltekit/executor.ts, packages/sveltekit/src/generators/application/lib/targets.ts
The `@nrwl/workspace:run-commands` executor is deprecated and scheduled for removal in Nx 16. This executor is being moved to `nx:run-commands`.
Consumers of Nxext executor delegating to `@nrwl/workspace:run-commands` receive a deprecation warning about this when running `@nxext/capacitor:cap`.
Projects with targets generated by Nxext receive a deprecation warning about this when the generated targets use the `@nrwl/workspace:run-commands` generator.
=> refactor: migrate to `nx:run-commands`

packages/capacitor/package.json
`@nrwl/devkit` has a peer dependency on `nx` so we must specify `nx` in our (peer) dependencies.
Change based on the outcome of #839.
=> chore(capacitor): list `nx` as peer dependency

packages/capacitor/package.json
This removes warnings for consumers using a version of Nx dependencies having the same major version.
Change based on the outcome of #841.
=> chore(capacitor): use version ranges for dependencies

packages/capacitor/package.json
[NPM](https://www.npmjs.com/package/@nxext/capacitor) is pointing to the Nxtend homepage & git repository
=> Update capacitor homepage & git repository

packages/capacitor/src/executors/cap/executor.ts
Using nxs implementation of runCommand inside the capacitor executor prevents the capacitor cli from being interactive
This PR uses execSync to execute the capacitor cli command
potentially fixes: #925
=> Use execSync in capacitor executor

packages/stencil/package.json
When I tried to install @nxext/stencil@16.3.0 it gave a peer dependency error as this hadn't been updated to 3.4.0.
=> fix(stencil): update stencil peer dep to correct version

CONTRIBUTING.md, docs/docs/nxext/contributing.md
Since pnpm is the package manager of this repository, it make sense to go ahead and update the references in the docs.
I removed the setting up a local registry as the commands for local-registry didn't exist. 
There are `start-local-registry` and `stop-local-registry` scripts, however those looks to be used mostly for pipeline testing. I think if we want repurpose that section to rely on those scripts I think that might be worth a follow up PR.
=> chore(docs): replace yarn references for pnpm

packages/solid/src/generators/library/schema.json
Vitest is a valid value for the unit test runner option, but it's missing from the schema file, therefore it's not possible to use it as NX validates the inputs against the schema.
This PR adds the vitest option to the schema.
=> fix(solid): add missing vitest enum value to the library schema

docs/docs/nxext/overview.md, docs/index.md
This PR is to add the Github link to the `@nxext/nx-extensions-ionic`.  If it is better, I can move the .md files for ionic-angular and ionic-react to this repo instead.
=> update docs to include link to ionic

packages/stencil/src/executors/stencil-runtime/prepare-config-and-outputarget-paths.ts
Small refactor to cover an edge case when specified projectRoot and distDir are the same, best not to update `package.json` file
=> chore(stencil): Don't copy the packageJson when specified distDir is same as projectRoot

packages/stencil/src/executors/build/executor.ts
No need to check for dep build status on same targetName when explicit `dependsOn` is specified
=> fix(stencil): Don't look for dependencies build status on same targetName when dependsOn is specified

packages/stencil/src/stencil-core-utils/lib/plugins.ts
* Addressed critical exception preventing Buildable Angular/React integrations with Stencil.
=> fix(stencil): Resolve exception when adding Angular output target (#1065)

docs/docs/sveltekit/generators.md, e2e/utils/index.ts, packages/sveltekit/src/generators/application/generator.ts, packages/sveltekit/src/generators/application/lib/install-dependencies.ts, packages/sveltekit/src/generators/application/schema.d.ts, packages/sveltekit/src/generators/application/schema.json, packages/sveltekit/src/generators/utils/versions.ts, pnpm-lock.yaml
This PR should implement the requested changes as per #1078 
I was unable to test it locally via the guide in Contributions.md
When I created the playground it seemed to fail but created an empty `proj` folder and a `packages` folder which I suppose symlinks to the real ones in the root folder?. 
When I then tried to run the app sveltekit generator it said it could not be found. When I ran the `nx g app` command it only listed preact, stencil and svelte and possible options, skipping both solid and sveltekit.
I'd highly appreciate if you can test these changes locally and provide feedback. Upgrading the versions should not require any changes to the current generator code in terms of basic routes, pages and layouts generated.
=> Sveltekit versions upgrade and CLI override

packages/stencil/src/executors/stencil-runtime/stencil-process.spec.ts, packages/stencil/src/executors/stencil-runtime/stencil-process.ts
Hey!
From @stencil/core@14.17.0 onward, the following error occurs for executors 'build', 'test', 'e2e', and 'serve': `Cannot read properties of undefined (reading 'validateConfig')`.
This issue stems from `globalThis.stencil` not being properly set within the `loadCoreCompiler` function.
To resolve this, the `loadCoreCompiler` function has been updated to ensure proper initialization of `globalThis.stencil` by assigning the imported compiler module if `globalThis.stencil` is undefined.
Additionally, I have added a test case in `stencil-process.spec.ts` to validate the correct initialization of `globalThis.stencil` by `loadCoreCompiler`.
I have tested the fix by upgrading the '@stencil/core' package from version 4.12.6 to 4.17.0 within this repo and running the tests in …
=> fix(stencil): resolve `validateConfig` error from @stencil/core@14.17.0 onward.

docs/docs/nxext/overview.md, docs/docs/vite/overview.md, docs/docs/vitest/overview.md
https://nx.dev/nx-community is looks moved to https://nx.dev/community
And some minor updates.
=> docs(nxext): update nx-community link

packages/stencil/src/executors/stencil-runtime/stencil-config.ts
`context.workspace` field is deprecated since Nx@17 and seems to be removed in Nx@20; `context.projectsConfigurations` and be used instead.
This change makes **@nxext/stencil** compatible with Nx@20 without breaking compatibility with previous versions.
=> fix(stencil): support Nx `context.projectsConfigurations`

docs/index.md, package.json
- Link main element to make them clickable to the start of their docs. 
- Add a new `start:docs` script, to let new contributor understand how to run the doc locally
Lower the amount of click needed to find what we want's : )
=> feat(docs/index): links

packages/ionic-angular/src/generators/configuration/generator.spec.ts, packages/ionic-angular/src/generators/configuration/lib/files.ts
=> fix(ionic-angular): correctly remove app files

packages/capacitor/project.json, packages/ionic-angular/project.json, packages/ionic-react/project.json, packages/preact/project.json, packages/solid/project.json, packages/stencil/project.json, packages/svelte/project.json, packages/sveltekit/project.json
Look like Nx release is used and not legacy `publish.mjs` script
Cleanup publish tasks
=> fix(release): cleanup publish task

packages/stencil/src/executors/stencil-runtime/stencil-config.ts
The change ensures that the `strictConfig` object properties have default values if not provided in the `loadedConfig` or if `loadedConfig` is undefined.
When looking at the code, `const loadedConfig = loadConfigResults.config` where `loadConfigResults` results from an attempt to load a config:
```ts
const loadConfigResults = await loadConfig({
config,
configPath,
logger,
sys,
});
const loadedConfig = loadConfigResults.config;
```
meaning, perhaps, it could not be loaded at a certain point (_according to the `LoadConfigResults` interface declaration on `@stencil/core`_)
```ts
/**
* Results from an attempt to load a config. The values on this interface
* have not yet been validated and are not ready to be used for arbitrary
* operations around the codebase.
*/
export interface …
```
=> fix(Stencil): ensure `strictConfig` properties has default values if `loadedConfig` is undefined

packages/stencil/src/generators/make-lib-buildable/make-lib-buildable.spec.ts, packages/stencil/src/generators/make-lib-buildable/make-lib-buildable.ts
Related issue: https://github.com/nxext/nx-extensions/issues/1168
=> #1168 replace autoDefineCustomElements with customElementsExportBehavior 'auto-define-custom-elements'
